def show_folds_fun(self):
    """
    Function shows number of folds, generated by KFold option from sklearn
    python pacakage, and number of training and testing data in every fold.

    Args:
        /
    Returns:
        Number of folds and number of trained/test data in every fold.
        
    """
    cnt = 1
    for train_index, test_index in self.kfold.split(self.X, self.y):
        print(f'Fold:{cnt}, Train set: {len(train_index)}, Test set:{len(test_index)}')
        cnt += 1